/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6eLXIG6yBWU
 */

import { useState } from "react";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import Image from "../../assets/contact.png";

export function Contactform() {
  const [result, setResult] = useState("Submit");

  const sendMessage = async (event: any) => {
    event.preventDefault();
    setResult("Sending....");
    const formData = new FormData(event.target);

    formData.append("access_key", "661cbf51-5187-48b4-9c86-15d3359b4608");

    const response = await fetch("https://api.web3forms.com/submit", {
      method: "POST",
      body: formData,
    });

    const data = await response.json();

    if (data.success) {
      setResult("Sent!");
      event.target.reset();
    } else {
      console.log("Error", data);
      setResult(data.message);
    }
  };

  return (
    <div className="container grid gap-12 px-4 pt-20 md:pt-16 md:grid-cols-2">
      <form onSubmit={sendMessage} className="space-y-4">
        <div className="space-y-2">
          <h1 className="text-amber text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl/none">
            Contact us
          </h1>

          <p className="text-gunmetal dark:text-gray-400">
            Feel free to reach out for any questions and estimates on pricing.
          </p>
        </div>
        <div className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2 ">
              <Label className="text-amber" htmlFor="name">
                Name
              </Label>
              <Input name="name" placeholder="Enter your name" required />
            </div>
            <div className="space-y-2">
              <Label className="text-amber" htmlFor="email">
                Email
              </Label>
              <Input
                name="email"
                placeholder="Enter your email"
                type="email"
                required
              />
            </div>
          </div>
          <div className="space-y-2">
            <Label className="text-amber" htmlFor="subject">
              Phone Number
            </Label>
            <Input name="subject" placeholder="Enter your number" required />
          </div>
          <div className="space-y-2">
            <Label className="text-amber" htmlFor="message">
              Message
            </Label>
            <Textarea
              className="min-h-[100px]"
              name="message"
              placeholder="Enter your message..."
            />
          </div>
          <div className="flex flex-row justify-between">
            <Button className="my-auto" type="submit">
              {result}
            </Button>
            <div className="flex flex-col lg:flex-row items-start  gap-2  max-w-sm text-center right-3 top-24 md:top-44">
              <div className="flex  items-center gap-2">
                <div className="rounded-full p-3 bg-amber dark:bg-gray-800">
                  <PhoneIcon className="w-4 h-4" />
                </div>
                <p className="text-sm text-amber font-medium">
                  {" "}
                  (863) 843-5932
                </p>
              </div>
              <div className="flex items-center gap-2">
                <div className="rounded-full p-3 bg-amber dark:bg-gray-800">
                  <MailIcon className="w-4 h-4" />
                </div>
                <p className="text-sm text-amber font-medium">
                  Virtuesod@gmail.com
                </p>
              </div>
            </div>
          </div>
        </div>
      </form>
      <div className="hidden items-center md:flex">
        <img
          alt="Contact us"
          className=" object-cover"
          height="400"
          src={Image}
          style={{
            aspectRatio: "700/400",
            objectFit: "contain",
          }}
          width="600"
        />
      </div>
    </div>
  );
}
function PhoneIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  );
}

function MailIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  );
}
