/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rKuREt9NSZH
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import bahia from "../../assets/bahia.jpg";
import bermuda from "../../assets/bermuda.jpg";
import citra from "../../assets/citrablue_staugustine.jpg";
import floratam from "../../assets/floratam.jpg";
import zoysia from "../../assets/zoysia.jpg";

import { useState } from "react";

export function Productaccordion() {
  const [expandedIndex, setExpandedIndex] = useState(-1);

  const toggleDescription = (index: number) => {
    setExpandedIndex(index === expandedIndex ? -1 : index);
  };

  return (
    <div className="mb-12 max-w-[1200px] w-10/12 mx-auto overflow-hidden rounded-lg shadow-lg dark:divide-gray-800">
      {" "}
      <div className="grid divide-y my-1 bg-prime dark:bg-gray-950 divide-gray-200">
        <div
          className="flex items-center justify-between gap-4 p-4 cursor-pointer"
          onClick={() => toggleDescription(0)}
        >
          <div className="flex items-center gap-4">
            <img
              alt="Product Image"
              className="aspect-square object-cover rounded-full border border-gray-200 w-16 dark:border-gray-800"
              height={100}
              src={bahia}
              width={100}
            />
            <div className="font-semibold text-accented">Bahia</div>
          </div>
          <ChevronDownIcon
            className={` text-accented w-4 h-4 fill-muted transition-transform ${
              expandedIndex === 0 ? "rotate-[-45deg] translate-y-0.5" : ""
            }`}
          />
        </div>
        <div
          style={{ backgroundImage: `url(${bahia})` }}
          className={`p-4 grid gap-4 text-sm leading-loose ${
            expandedIndex === 0 ? "" : "hidden"
          }`}
        >
          <p className="bg-white bg-opacity-75 p-2">
            Bahia grass (Paspalum notatum) is a warm-season grass that is
            well-suited for tropical and subtropical regions, including
            Southwest Florida. It is known for its coarse texture, deep-green
            color, and durability. Bahia grass is popular for lawns, pastures,
            and roadside applications due to its ability to thrive in various
            soil types and its tolerance for drought and heat.
          </p>
        </div>
      </div>
      {/* Repeat the structure for each product */}
      <div className="grid divide-y bg-prime my-1 dark:bg-gray-950 divide-gray-200">
        <div
          className="flex items-center justify-between gap-4 p-4 cursor-pointer"
          onClick={() => toggleDescription(1)}
        >
          <div className="flex items-center gap-4">
            <img
              alt="Product Image"
              className="aspect-square object-cover rounded-full border border-gray-200 w-16 dark:border-gray-800"
              height={100}
              src={bermuda}
              width={100}
            />
            <div className="font-semibold text-accented">Bermuda</div>
          </div>
          <ChevronDownIcon
            className={`text-accented w-4 h-4 fill-muted transition-transform ${
              expandedIndex === 1 ? "rotate-[-45deg] translate-y-0.5" : ""
            }`}
          />
        </div>
        <div
          style={{ backgroundImage: `url(${bermuda})` }}
          className={` p-4 grid gap-4 text-sm leading-loose ${
            expandedIndex === 1 ? "" : "hidden"
          }`}
        >
          <p className="bg-white bg-opacity-75 p-2">
            Bermuda grass (Cynodon dactylon) is a warm-season grass known for
            its fine texture, lush green appearance, and resilience. It is a
            popular choice for lawns, sports fields, and golf courses in warm
            climates, including Southwest Florida. Bermuda grass is well-adapted
            to the heat and can withstand periods of drought, making it a
            versatile option for landscapes.
          </p>
        </div>
      </div>
      {/* Repeat the structure for each product */}
      <div className="grid divide-y my-1 bg-prime dark:bg-gray-950 divide-gray-200">
        <div
          className="flex items-center justify-between gap-4 p-4 cursor-pointer"
          onClick={() => toggleDescription(2)}
        >
          <div className="flex items-center gap-4">
            <img
              alt="Product Image"
              className="aspect-square object-cover rounded-full border border-gray-200 w-16 dark:border-gray-800"
              height={100}
              src={citra}
              width={100}
            />
            <div className="font-semibold text-accented">Citra</div>
          </div>
          <ChevronDownIcon
            className={`text-accented w-4 h-4 fill-muted transition-transform ${
              expandedIndex === 2 ? "rotate-[-45deg] translate-y-0.5" : ""
            }`}
          />
        </div>
        <div
          style={{ backgroundImage: `url(${citra})` }}
          className={`p-4 grid gap-4 text-sm leading-loose ${
            expandedIndex === 2 ? "" : "hidden"
          }`}
        >
          <p className="bg-white bg-opacity-75 p-2">
            CitraBlue is a new variety of St Augustine sod. It's a warm-season
            grass that was specifically developed for warm climates - like those
            found in Florida! One of the cool things about CitraBlue grass is
            that there was a five-year trial done on farms all across Florida to
            test its viability and performance in different areas.
          </p>
        </div>
      </div>
      <div className="grid divide-y my-1 bg-prime dark:bg-gray-950 divide-gray-200">
        <div
          className="flex items-center justify-between gap-4 p-4 cursor-pointer"
          onClick={() => toggleDescription(3)}
        >
          <div className="flex items-center gap-4">
            <img
              alt="Product Image"
              className="aspect-square object-cover rounded-full border border-gray-200 w-16 dark:border-gray-800"
              height={100}
              src={floratam}
              width={100}
            />
            <div className="font-semibold text-accented">Floratam</div>
          </div>
          <ChevronDownIcon
            className={`text-accented w-4 h-4 fill-muted transition-transform ${
              expandedIndex === 3 ? "rotate-[-45deg] translate-y-0.5" : ""
            }`}
          />
        </div>
        <div
          style={{ backgroundImage: `url(${floratam})` }}
          className={`p-4 grid gap-4 text-sm leading-loose ${
            expandedIndex === 3 ? "" : "hidden"
          }`}
        >
          <p className="bg-white bg-opacity-75 p-2">
            Floratam is a cultivar of St. Augustine grass (Stenotaphrum
            secundatum) that has been developed for its tolerance to heat,
            making it a popular choice for lawns in warm climates. St. Augustine
            grass, in general, is known for its lush, broad blades and a
            carpet-like appearance. Floratam, in particular, has distinctive
            characteristics that set it apart.
          </p>
        </div>
      </div>
      <div className="grid divide-y  bg-prime dark:bg-gray-950 divide-gray-200">
        <div
          className="flex items-center justify-between gap-4 p-4 cursor-pointer"
          onClick={() => toggleDescription(4)}
        >
          <div className="flex items-center gap-4">
            <img
              alt="Product Image"
              className="aspect-square object-cover rounded-full border border-gray-200 w-16 dark:border-gray-800"
              height={100}
              src={zoysia}
              width={100}
            />
            <div className="font-semibold text-accented">Zoysia</div>
          </div>
          <ChevronDownIcon
            className={`text-accented w-4 h-4 fill-muted transition-transform ${
              expandedIndex === 4 ? "rotate-[-45deg] translate-y-0.5" : ""
            }`}
          />
        </div>
        <div
          style={{ backgroundImage: `url(${zoysia})` }}
          className={`p-4 grid gap-4 text-sm leading-loose ${
            expandedIndex === 4 ? "" : "hidden"
          }`}
        >
          <p className="bg-white bg-opacity-75 p-2">
            Zoysia grass is a warm-season grass known for its dense growth, fine
            texture, and lush green appearance. It's a popular choice for lawns,
            golf courses, and landscapes in warm and tropical climates,
            including Southwest Florida. Zoysia grass varieties are
            characterized by their tolerance to heat, drought resistance, and
            ability to form a dense and weed-resistant turf.
          </p>
        </div>
      </div>
    </div>
  );
}

function ChevronDownIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}
